project:
  type: website
  output-dir: docs
website:
  title: "Notes on Quantum Computing"
  favicon: kika.jpeg
  navbar:
    right:
      - about.qmd
  google-analytics: "G-1154MLY31V"
format:
  html:
    theme: cosmo
    css: styles.css
    
listing:
  contents: posts
  type: default
  image-align: left
  image-height: 150px
  fields: [date, title, description, categories, image]



